/**
 * One-shot initialisation of the shared config volume (service `penpotos-init`).
 *
 * - Generates the secrets on the first run (never overwrites existing ones), so the
 *   compose file needs no hand-edited passwords or keys.
 * - (Re)writes small start scripts that let the official Penpot images read those
 *   secrets from files (the images only read them from environment variables).
 */
import { randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

export const SECRET_FILES = ["postgres_password", "penpot_secret_key", "penpotos_secret_key", "internal_token"] as const;

const header = (what: string) => `#!/bin/bash
# Generated by penpotos-init – starts the ${what} with secrets from the PenpotOS config volume.
# Environment variables, when set, take precedence over the generated files.
set -e
CFG="\${PENPOTOS_CONFIG_DIR:-/config}"
read_cfg() { tr -d '\\n' < "$CFG/$1"; }
export PENPOT_SECRET_KEY="\${PENPOT_SECRET_KEY:-$(read_cfg penpot_secret_key)}"
if [ -z "$PENPOT_PUBLIC_URI" ]; then
  if [ -s "$CFG/public_url" ]; then export PENPOT_PUBLIC_URI="$(read_cfg public_url)"; else export PENPOT_PUBLIC_URI="http://localhost:9001"; fi
fi
`;

export const SCRIPTS: Record<string, string> = {
  "run-backend.sh":
    header("Penpot backend") +
    `export PENPOT_DATABASE_PASSWORD="\${PENPOT_DATABASE_PASSWORD:-$(read_cfg postgres_password)}"
cd /opt/penpot/backend
exec bash run.sh
`,
  "run-exporter.sh":
    header("Penpot exporter") +
    `cd /opt/penpot/exporter
exec node app.js
`,
};

/** Environment variables that, when set, define the secret instead of a generated value. */
export const SECRET_ENV: Record<(typeof SECRET_FILES)[number], string> = {
  postgres_password: "POSTGRES_PASSWORD",
  penpot_secret_key: "PENPOT_SECRET_KEY",
  penpotos_secret_key: "PENPOTOS_SECRET_KEY",
  internal_token: "PENPOTOS_INTERNAL_TOKEN",
};

function writeReadOnly(file: string, value: string) {
  fs.rmSync(file, { force: true });
  fs.writeFileSync(file, value + "\n", { mode: 0o444 });
}

export function initConfigDir(dir: string, envVars: NodeJS.ProcessEnv = process.env): { created: string[]; fromEnv: string[] } {
  fs.mkdirSync(dir, { recursive: true });
  const created: string[] = [];
  const fromEnv: string[] = [];
  for (const name of SECRET_FILES) {
    const file = path.join(dir, name);
    const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8").trim() : "";
    const provided = envVars[SECRET_ENV[name]]?.trim();
    if (provided && !provided.startsWith("ZMEN-")) {
      // Values from .env stay authoritative.
      if (provided !== current) writeReadOnly(file, provided);
      fromEnv.push(name);
      continue;
    }
    if (current) continue;
    // Hex keeps the values safe for URLs, shell scripts and connection strings.
    writeReadOnly(file, randomBytes(32).toString("hex"));
    created.push(name);
  }
  for (const [name, content] of Object.entries(SCRIPTS)) {
    const file = path.join(dir, name);
    fs.rmSync(file, { force: true });
    fs.writeFileSync(file, content, { mode: 0o555 });
  }
  return { created, fromEnv };
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const dir = process.env.PENPOTOS_CONFIG_DIR || "/config";
  try {
    const { created, fromEnv } = initConfigDir(dir);
    console.log(
      `penpotos-init: ${created.length ? `generated ${created.join(", ")}` : "no new secrets"}` +
        `${fromEnv.length ? `, taken from environment: ${fromEnv.join(", ")}` : ""} (${dir})`,
    );
  } catch (err) {
    console.error(`penpotos-init: cannot write to ${dir}:`, err);
    process.exit(1);
  }
}
